// Generated by CoffeeScript 1.8.0
(function() {
  var Fruit, db, models, yamldb,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  yamldb = require('./lib/yamldb');

  Fruit = (function(_super) {
    __extends(Fruit, _super);

    function Fruit() {
      return Fruit.__super__.constructor.apply(this, arguments);
    }

    Fruit.prototype.model = 'Fruit';

    Fruit.defaults({
      handle: '',
      name: '',
      price: 0.00,
      description: '',
      images: []
    });

    return Fruit;

  })(yamldb.Model);

  models = {
    Fruit: Fruit
  };

  db = new yamldb.Database('testdata', models);

  db.loadFiles('Fruit', function(err, objs) {
    console.log('Error: ', err);
    return console.log('Data: ', objs);
  });

}).call(this);
